#!/usr/bin/env python

from gi.repository import Gtk, GObject, Gdk
from uiStart import StarteratorWindow


def gui():
	GObject.threads_init()
	Gdk.threads_init()
	win = StarteratorWindow()
	win.connect('delete-event', Gtk.main_quit)
	win.show_all()
	Gdk.threads_enter()
	Gtk.main()
	Gdk.threads_leave()

if __name__ == "__main__":
	gui()